name: Workflowtest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: piptest
      env:
        NAME: ${{ secrets.NAME }}
      run: |
        pip list
        echo $NAME

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to ALIYUN Hub
      uses: docker/login-action@v2
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.ALIYUN_NAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: registry.cn-shanghai.aliyuncs.com/pmrdjango/workflowtest:0.1
        build-args: |
            DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}

    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        # Private key part of an SSH key pair,ssh 连接密钥 去除上下两行
        SSH_PRIVATE_KEY: ${{ secrets.ACCESS_KEY_SECRET }}
        # Remote host 服务器ip
        REMOTE_HOST: ${{ secrets.ECS_CLUSTER_ID }}
        # Remote user   #root
        REMOTE_USER: ${{ secrets.ACCESS_KEY_ID }} 
        
        # Target directory,把当前的项目代码目标拷贝到Target目录 /opt/DjangoChatGPTAPI
        TARGET:  "/opt/workflowtest"
        
        #跑一些脚本
 	      SCRIPT_AFTER: |

          #docker login --username=${{ secrets.ALIYUN_NAME }} registry.cn-shanghai.aliyuncs.com --password=${{ secrets.ALIYUN_PASSWORD }}
          docker pull registry.cn-shanghai.aliyuncs.com/pmrdjango/workflowtest:0.1